version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: installing dependencies
          command: npm install
      - run:
          name: Run an unit test
          command: npm test

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git

# the app is tested before being deployed to Heroku.

workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test